#!/bin/bash
export PATH=/opt/puppetlabs/bin:$PATH
puppet resource package git ensure=present
puppet resource package apache2 ensure=present
puppet resource service apache2 ensure=running
puppet resource file /tmp/22050023/clone ensure=absent force=true
puppet resource file /tmp ensure=directory
puppet resource file /tmp/22050023 ensure=directory
puppet resource file /tmp/22050023/clone ensure=directory
cd /tmp/22050023/clone
git clone https://github.com/KyawRP/22050023_repo.git
#cp -p /tmp/22050023/clone/22050023_repo/22050023_index.html /var/www/html/index.html
cp -p /tmp/22050023/clone/22050023_repo/22050023_index.html /var/www/html
